### PR TITLE
Added Boxzones for qb-target

### PR DESCRIPTION
**Pull request by D40G**
Added BoxZones for banks and TargetModels for atms.

### CODE REVIEW

**Review by D40G — COMMENTED** [review]
turned off debug poly

**Comment by ImpulseFPS** [comment]
why not just use models of ATM and use ped models for targeting?

**Comment by DaShizz** [comment]
> why not just use models of ATM and use ped models for targeting?
thought about it but,
Haven't tested yet, but theory is if ped is used you could potentially use that same ped if they're running around the map to access the bank

**Comment by ImpulseFPS** [comment]
> > why not just use models of ATM and use ped models for targeting?
> > thought about it but,
> > Haven't tested yet, but theory is if ped is used you could potentially use that same ped if they're running around the map to access the bank

Can you test the changes i made to your PR? thanks

**Comment by DaShizz** [comment]
@ImpulseFPS it works!

**Review by D40G — COMMENTED** [review]
It works

**Pull request merged**
